spring:
  thymeleaf:
    cache: false
  profiles:
    active: development
#  datasource:
#    url: jdbc:mysql:///:3306/readList
#    username: root
#    password: yesyes
#    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8081 #8443
#  ssl:
#    key-store: classpath:mykeys.jks
#    key-password: mmdxjj
#    key-store-password: mmdxjj

logging:
  level:
    root: INFO
    org.spring.framework.security: DEBUG

amazon:
  associateId: dong


---

spring:
profiles: development
logging:
  level:
  root: DEBUG

---

  spring:
  profiles: production
  logging:
    path: /temp/
    file: BookWorm.log
    level:
    root: WARN
